DATA_SET:
  name: 'CIFAR-10'  # MNIST, CIFAR-10
  root: '../data'
  source: 'raw'   # raw, distilled
  batch_size: 128
  num_workers: 0
TASK:
  train: True
  test: True
DISTILL:
  load_dir: 'output'
  d_steps: 10
  d_epochs: 3
  num_per_class: 1
TRAIN:
  # dataset
  augment: True
  # Task Model
  model: 'AlexCifarNet'
  optimizer: 'SGD'
  scheduler: 'CosineAnnealing'
  tloss_crit: 'CE'
  # Hyperparameters
  epochs: 200
  lr: 0.1
  SGD:
    weight_decay: 0.0005
    momentum: 0.9
  CosineAnnealing:
    lr_min: 0.001
  # features
  test_intv: 5
TAUG:
  # features
  load: False
  save: True
  load_dir: 'output'
  output_dir: 'output'
  # augmentation type
  name: 'CIFAR-10'
  aug_type: 'Auto'
  random_apply: True
  # hyper parameters
  search_intv: 3
  p_lr: 0.001
  p_decay_factor: 0.003
  k_ops: 1
  temp: 1.0
  delta: 0.0
